spring.application.name=civicflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/civicflow
spring.datasource.username=postgres
spring.datasource.password=OMK123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080